spring:
  profiles:
    include: log


MyRpc:
  service:
    name:
    port: 0
  register:
    address: nacos://127.0.0.1:8848
    auth:
      enabled: false
      userName: 123
      password: 123
  net:
    localHost:
    ChannelType: NIO
    RequestTimeOut: 1000
    ssl:
      enable: true
      CACrtPath: 'ca.crt'
      ServerCrtPath: 'server.crt'
      PrivateKeyPath: 'server.pem'
    protocol:
      SerializableType: JSON
      EncryptionMethod:
        name: AES
        SecretKey: 'YBO24VQ6fturtdAz+6YQ5Q=='







